name: EC2 Connectivity Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ec2-connection:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
     # Step 2: Add the EC2 private key to the SSH agent
      - name: Add EC2 private key to SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      # Step 3: Test the SSH connection to EC2 instance
      - name: Test SSH connection to EC2
        run: |
          echo "Testing SSH connection to EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa devops@${{ secrets.EC2_PUBLIC_IP }} "echo 'Connection successful!'"   
